### ISSUE TITLE
Error in JSON Sample

### ISSUE THREAD

**Issue by mowata** [jlinclabs/jlinc-spec#1]
Hi Victor,

I was unable to parse the example JSON for the OPTIONS Request, as it appears to be missing a comma to separate two fields:

{
    "@context": "https://jlinclabs.org/context/v03/link-contract.jsonld",
    "Version": "0.3",
    "TermsAccept":
        [
          "http://customercommons.org/user-terms/user-submitted-term-2/",
          "http://customercommons.org/user-terms/user-submitted-term-1/"
        ],
    "DataAddress":"https://example.com/alice",
    "REFRequired": "Stellar:REF/GCRA6COW27CY5MTKIA7POQ2326C5ABYCXODBN4TFF5VL4FMBRHOT3YHU:GBBLIKUSGLQQEYDAMY63DEIEZOX72CEXDX7Y4N6XS4WARKGU7VLGASEY:1"
    "iat":1449180663,
    "JID": "84db1202ffb32ef561fb4c0ebb79b631750392c92e594cb57a8b2d449e81fe86",
    "PrvncAPI": "https://provenance.jlinclabs.com/api/prvnc"
}

Should have a comma after the "REFRequired" field value, before "iat"

Andy

**Comment by jlinc-victor** [comment]
Thanks Andy -- fixed now.
